// <auto-generated />
namespace Charity.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class i4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(i4));
        
        string IMigrationMetadata.Id
        {
            get { return "201701100748023_i4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
